### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by ded** [orlandov/node-sqlite#33]
```
    node.js:194
            throw e; // process.nextTick error, or 'error' event on first tick
                  ^
    Error: dlopen(/Users/dustin/workspace/twt/node_modules/sqlite/build/default/sqlite3_bindings.node, 1): Symbol not found: __ZN4node12EventEmitter20constructor_templateE
      Referenced from: /Users/dustin/workspace/twt/node_modules/sqlite/build/default/sqlite3_bindings.node
      Expected in: flat namespace
     in /Users/dustin/workspace/twt/node_modules/sqlite/build/default/sqlite3_bindings.node
        at Object..node (module.js:465:11)
        at Module.load (module.js:335:31)
        at Function._load (module.js:294:12)
        at Module.require (module.js:341:17)
        at require (module.js:352:17)
        at Object.<anonymous> (/Users/dustin/workspace/twt/node_modules/sqlite/sqlite.js:19:14)
        at Module._compile (module.js:420:26)
        at Object..js (module.js:459:10)
        at Module.load (module.js:335:31)
        at Function._load (module.js:294:12)
```

$ node -v 
v0.5.3-pre

sqlite v 1.0.4

**Comment by ded** [comment]
Try it yourself....

```
$ mkdir testapp
$ cd !$
$ npm install sqlite
$ touch app.js
```

``` js
// app.js
var sqlite = require('sqlite')
  , db = new sqlite.Database()
```

```
$ node app.js
```

baaaaaaaaaaaaaaaarrrrrrrffffffff

**Comment by soney** [comment]
Broken as of node v0.5.1, which seems to be the last numbered version with any mention of the EventEmitter library.
