### ISSUE TITLE
Install fails for Node v0.6.x

### ISSUE THREAD

**Issue by mcantelon** [orlandov/node-sqlite#38]
Hi Orlando and contributin' folks,

I'm using npm 1.0.104 and the n utility to switch versions of Node. I can install the sqlite module using Node v0.4.x, but not v0.6.x. with v0.6.x I get a long gory dump, as shown below:

<snip>
[3/6] cxx: src/database.cc -> build/Release/src/database_2.o
../src/database.cc: In static member function ‘static v8::Handlev8::Value Database::Open(const v8::Arguments&)’:
../src/database.cc:137: error: invalid conversion from ‘int (_)(eio_req_)’ to ‘void (_)(eio_req_)’
../src/database.cc:137: error:   initializing argument 1 of ‘eio_req\* eio_custom(void (_)(eio_req_), int, int (_)(eio_req_), void_)’
../src/database.cc: In static member function ‘static v8::Handlev8::Value Database::Close(const v8::Arguments&)’:
../src/database.cc:202: error: invalid conversion from ‘int (_)(eio_req_)’ to ‘void (_)(eio_req_)’
../src/database.cc:202: error:   initializing argument 1 of ‘eio_req_ eio_custom(void (_)(eio_req_), int, int (_)(eio_req_), void_)’
../src/database.cc: In static member function ‘static v8::Handlev8::Value Database::PrepareAndStep(const v8::Arguments&)’:
../src/database.cc:370: error: invalid conversion from ‘int (_)(eio_req_)’ to ‘void (_)(eio_req_)’
../src/database.cc:370: error:   initializing argument 1 of ‘eio_req_ eio_custom(void (_)(eio_req_), int, int (_)(eio_req_), void_)’
../src/database.cc: In static member function ‘static v8::Handlev8::Value Database::Prepare(const v8::Arguments&)’:
../src/database.cc:506: error: invalid conversion from ‘int (_)(eio_req_)’ to ‘void (_)(eio_req_)’
../src/database.cc:506: error:   initializing argument 1 of ‘eio_req_ eio_custom(void (_)(eio_req_), int, int (_)(eio_req_), void*)’
../deps/sqlite/sqlite3.c: In function ‘proxyGetHostID’:
../deps/sqlite/sqlite3.c:28396: warning: unused variable ‘timeout’
Waf: Leaving directory `/Users/mike/node_modules/sqlite/build'
Build failed:  -> task failed (err #1): 
    {task: cxx database.cc -> database_2.o}
npm ERR! error installing sqlite@1.0.4 Error: sqlite@1.0.4 preinstall:`node-waf configure build`
npm ERR! error installing sqlite@1.0.4`sh "-c" "node-waf configure build"`failed with 1
npm ERR! error installing sqlite@1.0.4     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing sqlite@1.0.4     at ChildProcess.emit (events.js:70:17)
npm ERR! error installing sqlite@1.0.4     at maybeExit (child_process.js:359:16)
npm ERR! error installing sqlite@1.0.4     at Process.onexit (child_process.js:395:5)
npm ERR! sqlite@1.0.4 preinstall:`node-waf configure build`
npm ERR!`sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the sqlite@1.0.4 preinstall script.
npm ERR! This is most likely a problem with the sqlite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.6.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "sqlite"
npm ERR! cwd /Users/mike/tmp/sqlite
npm ERR! node -v v0.6.6
npm ERR! npm -v 1.0.104
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mike/tmp/sqlite/npm-debug.log
npm not ok
</snip>

Elven rock,
Mike

**Comment by DarrellBrogdon** [comment]
I see the same problems with npm 1.0.105 and node 0.6.2.

**Comment by SpeCT** [comment]
I'm getting error as above.

node 0.6.8 and npm 1.1.0-2 (both latest at the moment)

**Comment by spiderik** [comment]
Hello Orlando, I plea for help too.

Build failed: -> task failed (err #1):
{task: cxx database.cc -> database_2.o}

Exactly the same problem as guys above. Mine is on iPad I-OS, installing it via (./build.sh)

Darwin Spiderik 11.0.0 Darwin Kernel Version 11.0.0: Wed Mar 30 18:51:10 PDT 2011; root:xnu-1735.46~10/RELEASE_ARM_S5L8930X iPad1,1 arm K48AP Darwin

Sqlite ver:
3.7.2

I would rly love to get this working :) Thanks a lot for any help.

**Comment by dmuth** [comment]
I'm seeing this exact issue, too.  This happens when building from source in node v0.6.10.

-- Doug

**Comment by andrewdeandrade** [comment]
Same issue with node v0.6.11

this part failed:
`node-waf configure build`

**Comment by brunomorency** [comment]
The solution seems to be moving to this package: https://github.com/developmentseed/node-sqlite3
API is very similar and you'll find the same contributors.
